services:
  app:
    build: .
    container_name: rrs-app
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: rrs-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "nc", "-z", "${DB_HOST}", "${DB_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db_data: